"use client";
import AppShell from "@/components/layout/AppShell";
import { Apple, Plus, Trash2, Sparkles, Flame, Beef, Wheat, Droplets, X, Camera } from "lucide-react";
import { useMemo, useState } from "react";
import { useNeurofit } from "@/lib/store";

const TARGETS={kcal:2000,protein:150,carbs:250,fat:70};
export default function Alimentacao(){
 const {currentUser,addFood,removeFood}=useNeurofit();
 const [showForm,setShowForm]=useState(false); const [meal,setMeal]=useState("Café da manhã"); const [desc,setDesc]=useState(""); const [kcal,setKcal]=useState(""); const [protein,setProtein]=useState(""); const [carbs,setCarbs]=useState(""); const [fat,setFat]=useState("");
 const today=new Date().toISOString().slice(0,10); const foods=currentUser.foods.filter(f=>f.date.slice(0,10)===today);
 const totals=useMemo(()=>foods.reduce((a,f)=>({kcal:a.kcal+f.kcal,protein:a.protein+f.protein,carbs:a.carbs+f.carbs,fat:a.fat+f.fat}),{kcal:0,protein:0,carbs:0,fat:0}),[foods]);
 function add(e:React.FormEvent){e.preventDefault();if(!desc)return;addFood({meal,description:desc,kcal:+kcal||0,protein:+protein||0,carbs:+carbs||0,fat:+fat||0});setDesc("");setKcal("");setProtein("");setCarbs("");setFat("");setShowForm(false)}
 const remaining=Math.max(0,TARGETS.kcal-totals.kcal);
 return <AppShell><div className="mobile-content">
  <header className="flex items-start justify-between gap-3"><div><p className="section-title">NUTRIÇÃO</p><h1 className="mt-2 text-[30px] font-black tracking-tight">Alimentação</h1><p className="mt-2 text-sm leading-6 text-[#7897ae]">Registre suas refeições e entenda como está seu dia.</p></div><div className="rounded-2xl bg-[#062b49] p-3 text-[#19dfff]"><Apple/></div></header>

  <section className="mt-5 rounded-[28px] border border-[#11527f] bg-[radial-gradient(circle_at_85%_10%,rgba(0,156,255,.20),transparent_38%),linear-gradient(145deg,#071a2a,#040a11)] p-5">
   <div className="flex items-center gap-5"><div className="relative h-28 w-28 shrink-0 rounded-full" style={{background:`conic-gradient(#12cfff ${Math.min(100,totals.kcal/TARGETS.kcal*100)*3.6}deg,#0b2438 0deg)`}}><div className="absolute inset-[8px] flex flex-col items-center justify-center rounded-full bg-[#06111b]"><Flame size={17} className="text-[#19dfff]"/><span className="mt-1 text-xl font-black">{totals.kcal}</span><span className="text-[9px] text-[#6f8ea5]">KCAL</span></div></div><div className="min-w-0"><p className="text-xs font-bold tracking-[.14em] text-[#6f8ea5]">HOJE</p><p className="mt-1 text-2xl font-black">{remaining} kcal</p><p className="mt-1 text-xs leading-5 text-[#7897ae]">restantes da meta de {TARGETS.kcal} kcal</p></div></div>
   <button onClick={()=>setShowForm(true)} className="blue-gradient mt-5 flex w-full items-center justify-center gap-2 rounded-2xl py-3.5 text-sm font-black"><Plus size={18}/> Adicionar refeição</button>
  </section>

  <section className="mt-4 grid grid-cols-3 gap-2">
    <Macro icon={<Beef size={16}/>} label="Proteína" value={`${totals.protein}g`} target={TARGETS.protein}/>
    <Macro icon={<Wheat size={16}/>} label="Carbo" value={`${totals.carbs}g`} target={TARGETS.carbs}/>
    <Macro icon={<Droplets size={16}/>} label="Gordura" value={`${totals.fat}g`} target={TARGETS.fat}/>
  </section>

  <section className="glass mt-4 rounded-[26px] p-5"><div className="flex items-center justify-between"><div><p className="section-title">REGISTROS</p><h2 className="mt-1 text-xl font-black">Refeições de hoje</h2></div><span className="rounded-full bg-[#062b49] px-3 py-1.5 text-xs font-bold text-[#19dfff]">{foods.length} {foods.length===1?'refeição':'refeições'}</span></div>
   {foods.length===0?<div className="mt-5 rounded-2xl border border-dashed border-[#17496c] bg-[#04101a] p-7 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#062b49] text-[#19dfff]"><Apple size={21}/></div><p className="mt-3 text-sm font-bold">Seu diário está vazio</p><p className="mt-1 text-xs leading-5 text-[#6f8da5]">Registre a primeira refeição e acompanhe seus macros ao longo do dia.</p><button onClick={()=>setShowForm(true)} className="mt-4 rounded-xl border border-[#155a86] px-4 py-2.5 text-xs font-bold text-[#19dfff]">Registrar agora</button></div>:<div className="mt-4 space-y-3">{foods.slice().reverse().map(f=><article key={f.id} className="rounded-2xl border border-[#123653] bg-[#04101a] p-4"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#062b49] p-2.5 text-[#19dfff]"><Apple size={17}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><div><p className="text-xs font-bold text-[#19dfff]">{f.meal}</p><p className="mt-1 font-bold leading-5">{f.description}</p></div><button onClick={()=>removeFood(f.id)} className="rounded-xl p-2 text-[#607f94] hover:bg-red-500/10 hover:text-red-300"><Trash2 size={16}/></button></div><div className="mt-3 grid grid-cols-4 gap-1.5"><Mini label="Kcal" value={f.kcal}/><Mini label="Prot." value={`${f.protein}g`}/><Mini label="Carbo" value={`${f.carbs}g`}/><Mini label="Gord." value={`${f.fat}g`}/></div></div></div></article>)}</div>}
  </section>

  <section className="mt-4 rounded-[26px] border border-[#123653] bg-[linear-gradient(145deg,#06131f,#030b12)] p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#062b49] p-2.5 text-[#19dfff]"><Sparkles size={18}/></div><div><p className="font-black">Quer uma análise?</p><p className="mt-1 text-xs leading-5 text-[#7897ae]">O NEUROFIT IA pode analisar o que você registrou e sugerir ajustes para seu objetivo.</p></div></div></section>

  {showForm&&<div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/75 p-0 backdrop-blur-sm" onClick={()=>setShowForm(false)}><form onSubmit={add} onClick={e=>e.stopPropagation()} className="w-full max-w-[430px] rounded-t-[30px] border border-[#164d73] bg-[#050d15] p-5 pb-[calc(22px+env(safe-area-inset-bottom))] shadow-[0_-20px_70px_rgba(0,100,255,.18)]"><div className="flex items-center justify-between"><div><p className="section-title">NOVO REGISTRO</p><h2 className="mt-1 text-2xl font-black">Adicionar refeição</h2></div><button type="button" onClick={()=>setShowForm(false)} className="rounded-xl border border-[#123653] p-2 text-[#7897ae]"><X size={18}/></button></div><div className="mt-5 space-y-3"><label className="block text-xs font-bold text-[#7897ae]">Refeição<select className="field mt-1.5" value={meal} onChange={e=>setMeal(e.target.value)}><option>Café da manhã</option><option>Almoço</option><option>Lanche</option><option>Jantar</option><option>Ceia</option></select></label><label className="block text-xs font-bold text-[#7897ae]">O que você comeu?<textarea required className="field mt-1.5 min-h-24" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Ex.: arroz, feijão, frango e salada"/></label><div className="grid grid-cols-2 gap-2"><Num label="Calorias" value={kcal} set={setKcal}/><Num label="Proteína (g)" value={protein} set={setProtein}/><Num label="Carbo (g)" value={carbs} set={setCarbs}/><Num label="Gordura (g)" value={fat} set={setFat}/></div><button className="blue-gradient flex w-full items-center justify-center gap-2 rounded-2xl py-3.5 font-black"><Plus size={18}/> Salvar refeição</button></div></form></div>}
 </div></AppShell>
}
function Macro({icon,label,value,target}:{icon:React.ReactNode;label:string;value:string;target:number}){const n=parseFloat(value)||0;const pct=Math.min(100,n/target*100);return <div className="glass rounded-2xl p-3"><div className="flex items-center gap-1.5 text-[#19dfff]">{icon}<span className="truncate text-[10px] font-bold text-[#7897ae]">{label}</span></div><p className="mt-2 text-lg font-black">{value}</p><div className="mt-2 h-1 overflow-hidden rounded-full bg-[#102437]"><div className="blue-gradient h-full rounded-full" style={{width:`${pct}%`}}/></div><p className="mt-1 text-[9px] text-[#5f7d94]">meta {target}g</p></div>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-lg bg-[#061522] p-2"><p className="text-[8px] text-[#5f7d94]">{label}</p><p className="mt-0.5 text-[10px] font-bold">{value}</p></div>}
function Num({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-[10px] font-bold text-[#7897ae]">{label}<input type="number" min="0" value={value} onChange={e=>set(e.target.value)} className="field mt-1"/></label>}
