// @ts-nocheck
"use client";
import AppShell from "@/components/layout/AppShell";import Link from "next/link";import {Dumbbell,Flame,Scale,Target,ArrowRight,Check,Clock,TrendingDown,Apple,Sparkles,ChevronRight} from "lucide-react";import {useNeurofit} from "@/lib/store";
export default function Dashboard(){const {currentUser,exercises}=useNeurofit();const p=currentUser.profile;const today=new Date().toISOString().slice(0,10);const workout=currentUser.workouts.find(w=>w.date===today)||currentUser.workouts[0];const done=workout?workout.exercises.reduce((a,id)=>a+Array.from({length:exercises.find(x=>x.id===id)?.sets||0},(_,i)=>currentUser.completedSets[`${id}:${i+1}`]?1:0).reduce((x,y)=>x+y,0),0):0;const total=workout?workout.exercises.reduce((a,id)=>a+(exercises.find(x=>x.id===id)?.sets||0),0):1;const bmi=p.height&&p.weight?p.weight/((p.height/100)**2):0;const progress=p.targetWeight&&p.weight?Math.max(0,Math.min(100,Math.round(Math.abs(p.weight-(currentUser.weights[0]?.weight||p.weight))/Math.max(1,Math.abs((currentUser.weights[0]?.weight||p.weight)-p.targetWeight))*100))):0;return <AppShell><div className="mobile-content">
 <section className="relative overflow-hidden rounded-[28px] border border-[#11446c] bg-[radial-gradient(circle_at_88%_5%,rgba(0,153,255,.28),transparent_38%),linear-gradient(145deg,#071524,#03070c)] p-5">
   <div className="absolute -right-10 -top-12 h-40 w-40 rounded-full bg-[#008dff]/10 blur-3xl"/>
   <p className="section-title">PAINEL NEUROFIT</p><h1 className="mt-2 text-[28px] font-black leading-tight">Olá, {p.name.split(" ")[0]} <span className="text-[#19dfff]">👋</span></h1><p className="mt-2 text-sm text-[#8ba5b7]">Seu objetivo: <span className="text-white">{p.goal||"Configure seu perfil"}</span></p>
   <div className="mt-5 grid grid-cols-2 gap-2"><MiniStat icon={<Scale size={16}/>} label="Peso atual" value={p.weight?`${p.weight.toFixed(1)} kg`:"—"}/><MiniStat icon={<Target size={16}/>} label="Meta" value={p.targetWeight?`${p.targetWeight.toFixed(1)} kg`:"—"}/></div>
 </section>
 <div className="mt-3 grid grid-cols-2 gap-3"><div className="glass rounded-2xl p-4"><div className="flex items-center gap-2 text-[#19dfff]"><Flame size={18}/><span className="text-xs font-bold text-[#7f99aa]">TREINOS</span></div><p className="mt-2 text-2xl font-black">{currentUser.workouts.filter(w=>w.completed).length}</p><p className="text-[11px] text-[#71899a]">concluídos</p></div><div className="glass rounded-2xl p-4"><div className="flex items-center gap-2 text-[#19dfff]"><TrendingDown size={18}/><span className="text-xs font-bold text-[#7f99aa]">IMC</span></div><p className="mt-2 text-2xl font-black">{bmi?bmi.toFixed(1):"—"}</p><p className="text-[11px] text-[#71899a]">referência</p></div></div>
 <section className="mt-4 overflow-hidden rounded-[28px] border border-[#0d5d96] bg-[linear-gradient(145deg,#071a2b,#04101b)] shadow-[0_18px_55px_rgba(0,92,180,.13)]"><div className="p-5"><div className="flex items-center justify-between"><div><p className="section-title">TREINO DE HOJE</p><h2 className="mt-2 text-[24px] font-black">{workout?.title||"Seu treino"}</h2><p className="mt-1 text-xs text-[#7897ae]">{workout?.exercises.length||0} exercícios · ~{workout?.duration||0} min</p></div><div className="rounded-2xl bg-[#062e4e] p-3 text-[#19dfff]"><Dumbbell/></div></div>
 {workout&&<div className="mt-5 space-y-2">{workout.exercises.map((id)=>{const e=exercises.find(x=>x.id===id)!;const sets=Array.from({length:e.sets},(_,i)=>!!currentUser.completedSets[`${id}:${i+1}`]).filter(Boolean).length;return <div key={id} className="flex items-center gap-3 rounded-2xl border border-[#123b5b] bg-[#05111c]/80 p-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#062c49] text-[#18caff]"><Dumbbell size={18}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{e.name}</p><p className="mt-0.5 text-[11px] text-[#6f8da5]">{e.sets} × {e.reps}</p></div>{sets===e.sets?<Check size={17} className="text-[#28e68a]"/>:<Clock size={17} className="text-[#617f96]"/>}</div>})}</div>}
 <div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[#102b42]"><div className="blue-gradient h-full rounded-full" style={{width:`${Math.round(done/total*100)}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-[#6e899d]"><span>{done}/{total} séries</span><span>{Math.round(done/total*100)}%</span></div>
 <Link href="/treino" className="blue-gradient mt-4 flex items-center justify-center gap-2 rounded-full py-3.5 text-xs font-black tracking-wider">{done>0?"CONTINUAR TREINO":"COMEÇAR TREINO"}<ArrowRight size={16}/></Link>
 </div></section>
 <section className="glass mt-4 rounded-[26px] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#062d4a] p-2.5 text-[#19dfff]"><Target size={19}/></div><div><p className="text-sm font-bold">Meta de peso</p><p className="text-[11px] text-[#71899c]">Seu progresso</p></div></div><span className="text-lg font-black text-[#19dfff]">{progress}%</span></div><div className="mt-4 h-2 rounded-full bg-[#102437]"><div className="blue-gradient h-full rounded-full" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-[10px] text-[#71899c]"><span>{p.weight||0} kg</span><span>{p.targetWeight||0} kg</span></div></section>
 <div className="mt-4 grid grid-cols-2 gap-3"><Quick href="/alimentacao" icon={<Apple size={19}/>} title="Nutrição" text={`${currentUser.foods.length} refeições`}/><Quick href="/assistente" icon={<Sparkles size={19}/>} title="NEUROFIT IA" text="Pergunte qualquer coisa"/></div>
 <Link href="/evolucao" className="glass mt-3 flex items-center gap-3 rounded-2xl p-4"><div className="rounded-xl bg-[#062d4a] p-2.5 text-[#19dfff]"><TrendingDown size={18}/></div><div className="flex-1"><p className="text-sm font-bold">Acompanhar evolução</p><p className="text-[11px] text-[#71899c]">{currentUser.weights.length} registros de peso</p></div><ChevronRight size={17} className="text-[#62839a]"/></Link>
 </div></AppShell>}
function MiniStat({icon,label,value}:{icon:React.ReactNode,label:string,value:string}){return <div className="rounded-2xl border border-[#123b5c] bg-[#030b13]/70 p-3"><div className="flex items-center gap-2 text-[#19dfff]">{icon}<span className="text-[10px] font-bold text-[#7791a3]">{label}</span></div><p className="mt-1 text-lg font-black">{value}</p></div>}
function Quick({href,icon,title,text}:{href:string,icon:React.ReactNode,title:string,text:string}){return <Link href={href} className="glass rounded-2xl p-4"><div className="rounded-xl bg-[#062d4a] p-2.5 text-[#19dfff] w-fit">{icon}</div><p className="mt-3 text-sm font-bold">{title}</p><p className="mt-1 text-[10px] leading-4 text-[#71899c]">{text}</p></Link>}
