// @ts-nocheck
"use client";
import AppShell from "@/components/layout/AppShell";
import {useEffect,useState} from "react";
import {Check,Clock,PlayCircle,TimerReset,X,Dumbbell,Trophy,ChevronLeft,Info} from "lucide-react";
import {useNeurofit} from "@/lib/store";

export default function Treino(){
 const {currentUser,exercises,toggleSet,addWorkoutCompletion}=useNeurofit();
 const today=new Date().toISOString().slice(0,10);
 const workout=currentUser.workouts.find(w=>w.date===today)||currentUser.workouts[0];
 const [selected,setSelected]=useState<string|null>(null);
 const [seconds,setSeconds]=useState(0); const [running,setRunning]=useState(false);
 useEffect(()=>{if(!running||seconds<=0)return;const t=setInterval(()=>setSeconds(s=>{if(s<=1){setRunning(false);return 0}return s-1}),1000);return()=>clearInterval(t)},[running,seconds]);
 const total=workout?.exercises.reduce((a,id)=>a+(exercises.find(x=>x.id===id)?.sets||0),0)||0;
 const done=workout?.exercises.reduce((a,id)=>{const e=exercises.find(x=>x.id===id)!;return a+Array.from({length:e.sets},(_,i)=>currentUser.completedSets[`${id}:${i+1}`]?1:0).reduce((x,y)=>x+y,0)},0)||0;
 const complete=done===total&&total>0;
 return <AppShell><div className="mobile-content">
   <div className="mb-4 flex items-center gap-3"><button onClick={()=>history.back()} className="rounded-full border border-[#123b5c] bg-[#06111b] p-2 text-[#8eb0c4]"><ChevronLeft size={20}/></button><div><p className="section-title">TREINO DE HOJE</p><h1 className="mt-1 text-2xl font-black">{workout?.title||"Seu treino"}</h1></div></div>
   <div className="glass rounded-2xl p-4"><div className="flex items-center justify-between"><div><p className="text-[11px] text-[#718da1]">PROGRESSO</p><p className="mt-1 text-xl font-black"><span className="text-[#19dfff]">{done}</span>/{total} séries</p></div><div className="text-right"><p className="text-[11px] text-[#718da1]">DURAÇÃO</p><p className="mt-1 font-bold">~{workout?.duration||0} min</p></div></div><div className="mt-3 h-1.5 rounded-full bg-[#102437]"><div className="blue-gradient h-full rounded-full transition-all" style={{width:`${total?done/total*100:0}%`}}/></div></div>
   <div className="mt-5 space-y-5">{workout?.exercises.map((id,idx)=>{const e=exercises.find(x=>x.id===id)!;const setsDone=Array.from({length:e.sets},(_,i)=>currentUser.completedSets[`${id}:${i+1}`]?1:0).reduce((a,b)=>a+b,0);return <section key={id} className="glass overflow-hidden rounded-[28px]">
     <button onClick={()=>setSelected(id)} className="relative block w-full text-left"><div className="exercise-video"><video src={e.video} autoPlay muted loop playsInline preload="metadata"/><div className="absolute left-4 top-4 rounded-full border border-[#1c86bd] bg-[#03111d]/90 px-3 py-1.5 text-xs font-bold text-[#18caff]">{e.muscle}</div><div className="absolute right-4 top-4 rounded-full bg-[#03111d]/80 p-2 text-[#18caff]"><PlayCircle size={18}/></div><div className="absolute bottom-4 left-4 rounded-full bg-[#008dff]/95 px-4 py-2 text-xs font-black shadow-lg"><PlayCircle size={15} className="mr-1 inline"/> VER EXECUÇÃO</div></div></button>
     <div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black tracking-[.16em] text-[#5f8ca9]">EXERCÍCIO {idx+1}</p><h2 className="mt-1 text-[23px] font-black">{e.name}</h2><p className="mt-1 text-xs text-[#7897ae]">{e.sets} séries · {e.reps} repetições · {e.rest}s descanso</p></div><div className="rounded-xl bg-[#062e4e] p-2.5 text-[#19dfff]"><Dumbbell size={18}/></div></div>
       <div className="mt-4 rounded-2xl border border-[#123653] bg-[#04101a] p-4"><div className="flex items-center gap-2"><Info size={15} className="text-[#19dfff]"/><p className="text-[11px] font-black tracking-[.14em] text-[#19dfff]">COMO EXECUTAR</p></div><div className="mt-3 space-y-2">{e.tips.map((tip,i)=><div key={tip} className="flex gap-2 text-sm leading-5 text-[#9ab2c3]"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#062b49] text-[10px] font-bold text-[#18caff]">{i+1}</span><span>{tip}</span></div>)}</div></div>
       <div className="mt-4 flex items-center justify-between"><p className="text-xs text-[#718da1]"><span className="font-bold text-white">{setsDone}</span> de {e.sets} séries concluídas</p><button onClick={()=>setSelected(id)} className="text-xs font-bold text-[#19dfff]">Detalhes →</button></div>
       <div className="mt-3 grid grid-cols-2 gap-2">{Array.from({length:e.sets},(_,i)=>{const checked=!!currentUser.completedSets[`${id}:${i+1}`];return <button key={i} onClick={()=>{toggleSet(id,i+1);if(!checked){setSeconds(e.rest);setRunning(true)}}} className={`rounded-xl border p-3 text-left transition ${checked?"border-[#10d987]/50 bg-[#0a3327]":"border-[#123653] bg-[#06111d]"}`}><span className="text-[10px] text-[#7897ae]">Série {i+1}</span><span className="mt-1 flex items-center justify-between text-sm font-bold">{e.reps} reps {checked?<Check size={16} className="text-[#28e68a]"/>:<span className="text-[#55748c]">○</span>}</span></button>})}</div>
       <button onClick={()=>{setSeconds(e.rest);setRunning(true)}} className="btn-ghost mt-3 flex w-full items-center justify-center gap-2 text-[#19dfff]"><Clock size={16}/> Iniciar descanso</button>
     </div></section>})}</div>
   {complete&&<div className="glass mt-5 rounded-3xl border-[#0d9f6f] p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-[#0a3327] p-3 text-[#28e68a]"><Trophy/></div><div><p className="font-black">Treino concluído! 🔥</p><p className="text-xs text-[#7897ae]">Excelente. Registre sua evolução e mantenha a consistência.</p></div></div><button onClick={addWorkoutCompletion} className="mt-4 w-full rounded-xl bg-[#10b981] py-3 font-bold text-white">Marcar treino concluído</button></div>}
   {seconds>0&&<div className="fixed bottom-24 left-1/2 z-50 w-[calc(100%-32px)] max-w-[398px] -translate-x-1/2 rounded-2xl border border-[#075c91] bg-[#04111d]/95 p-4 shadow-2xl backdrop-blur-xl"><div className="flex items-center gap-3"><TimerReset className="text-[#18caff]"/><div className="flex-1"><p className="text-[10px] text-[#7897ae]">DESCANSO</p><p className="text-2xl font-black">{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</p></div><button onClick={()=>{setSeconds(0);setRunning(false)}} className="rounded-lg p-2 text-[#7897ae]"><X size={17}/></button></div></div>}
   {selected&&<ExerciseModal id={selected} onClose={()=>setSelected(null)}/>}</div></AppShell>
}
function ExerciseModal({id,onClose}:{id:string;onClose:()=>void}){const {exercises}=useNeurofit();const e=exercises.find(x=>x.id===id)!;return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-black/75 p-0 backdrop-blur-sm sm:items-center sm:p-4" onClick={onClose}><div onClick={x=>x.stopPropagation()} className="glass max-h-[94dvh] w-full max-w-2xl overflow-auto rounded-t-[30px] p-5 sm:rounded-[30px] md:p-7"><div className="flex items-center justify-between"><div><p className="section-title">GUIA DE EXECUÇÃO</p><h2 className="mt-1 text-2xl font-black">{e.name}</h2></div><button onClick={onClose} className="rounded-xl border border-[#123653] p-2 text-[#7897ae]"><X/></button></div><div className="exercise-video mt-5 rounded-2xl overflow-hidden"><video src={e.video} autoPlay muted loop playsInline controls={false}/></div><div className="mt-4 grid grid-cols-3 gap-2"><Stat label="Músculo" value={e.muscle}/><Stat label="Séries" value={`${e.sets} × ${e.reps}`}/><Stat label="Descanso" value={`${e.rest}s`}/></div><h3 className="mt-6 font-bold">Como executar</h3><ol className="mt-3 space-y-2">{e.tips.map((tip,i)=><li key={tip} className="flex gap-3 rounded-xl border border-[#123653] bg-[#06111d] p-3 text-sm text-[#9ab2c3]"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#062b49] text-[#18caff]">{i+1}</span>{tip}</li>)}</ol><button onClick={onClose} className="blue-gradient mt-5 w-full rounded-xl py-3 font-bold">Entendi</button></div></div>}
function Stat({label,value}:{label:string,value:string}){return <div className="rounded-xl border border-[#123653] bg-[#06111d] p-3"><p className="text-[10px] text-[#7897ae]">{label}</p><p className="mt-1 truncate text-xs font-bold">{value}</p></div>}
